travis:
  secure:
    BINSTAR_TOKEN: gp9hrVEPYzBc6LAN9hAjs9hA+N4b1rgnEa9gsDXQw8SimtQ2PBHxtub+ruE/9YHEwo1sjWswnke1RWN92eZ6Q6n477QBGmwlhX4p5ylBQ/QCUc/hv1sotU6Dm8IHAvEA91TithCv1WxQdoopdfebc0o59JcVo2+wAQsWFL5P1Yz4VTMeFM5iCluWnWpObKPhAcqzjA7BtSzv+yQSD5JXEyXH35qNMrQg6ii6fKt+ocTVMqxuzuz1oscYOFqPCiYN6A5b82ypivh2lNNS3OwdS5/j4ewSpLhRPQqvKlYQo3/cgs3K2gFNgs061tCUO3d8pJQS5tL16LLeeNh9AL4UHtTqva8hddpKJ7byiGgqTWkDv8zRrSazMr9O4X1mzUFhVgEObvhPiwJu4Ma1ER6JsPu84lcgzpzaqS/CWm7NMC89MbMCNw5zjWcbDV1tHKBlc+POyIunKy7/dh9uwZ76PQhK3Im7mfTrpL5GVCGREYt3ErCbedF0cg+ftORV8s3FQp3+OH9m/6KftOWP2Wh0tzSI5BewT4By8OapD0Wiuqvt7B7IgzTLVm9c9epz0rd/pedPaM28L4h1C9scozlQTbGuTwzX4tlEPWx8SSdQaJHFyFhmJl75gmy2QWTE/7+x2M5XNoX1Ilq+zezKRUisICIJKiopRYaQaQlK6SL3QN4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
