travis:
  secure:
    BINSTAR_TOKEN: JXkW/9C4n91dtNvAuFt1AdXq7c2s6hl3mDuZOHP/nr6dgrivvLosehU5ynrj9GC1uNh1ThiLnZtgcdVJA+ryInZgQi2wmjYmUEyrB4x3AmhTK2r9Y99dxnkmCbiyJ9uwTHYdBZwWqjlENLSMTUqIMtqDGjrSchv9WmEc5D88YVWmRsZC0ZikH2IW//E9Y5Wn9GbB/zARka7zPKlv0J9xbPMWY/vkXorxZ8gAwVvQycrpu0zzJXR7o11eOeRnuGJJmI1/tcYdiemvolt2dt1qbePs3tlQUYiD8TezPmdnWf5YVMLdk9DOJscbbsJn6hSSGl00GLsbYwoEsNmePqnf8fvoncCO9SGLKRorMzfXXfEjLCNNfXAdcAi/g/QgfnD6rMnMAE3b+pnBAxbHq/AjzQ829+co8/KqRWFvSqfag37Li+RSk3WcoEqU2dpjfMUOgAhtKefQvq9u9WzsdQ7+WGspeeW4BkG/8SXpMobGcC/zy1fa4AxDh2djRByxaW0/AyRZkfr1mCXASt6Z37H6dZf+XRY+cDWizPfrWgy7UYNV2XaXlg9nbvzWc9kDMKQOk5eEO6HD5oo5oC9xycX9d/I9zocrPymFF1Qz7fNQzu2vIzuCUFEVjIxjKsdUVQyop5dwTv5MOh2X0LdTutzgjZkyl+icq9HmY6MVg5jC4jQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
